### ISSUE TITLE
pyzmq-static 2.1.11.2 test_ioloop fails due to some missing files

### ISSUE THREAD

**Issue by gavrie** [brandon-rhodes/pyzmq-static#2]
On pyzmq-static version 2.1.11.2, the ioloop code does not work correctly. It seems to be missing some files:

``` sh
host101: /tmp $ pip freeze|grep zmq
pyzmq-static==2.1.11.2
host101: /tmp $ python /usr/local/lib/python2.7/dist-packages/zmq/tests/test_ioloop.py 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/zmq/tests/test_ioloop.py", line 30, in <module>
    from zmq.eventloop import ioloop
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/__init__.py", line 3, in <module>
    from zmq.eventloop.ioloop import IOLoop
  File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/ioloop.py", line 56, in <module>
    from zmq.eventloop.platform.auto import set_close_exec, Waker
ImportError: No module named platform.auto
```

On pyzmq-static 2.1.7.1, this test passes correctly.

This issue was reproduced on both Mac OS X 10.6 and on Ubuntu 10.10.

Of course, the test failing is just a symptom -- my actual problem is that the ioloop part of pyzmq doesn't work in this version.

**Comment by brandon-rhodes** [comment]
The pyzmq-static project is now closing (yay!) because our functionality has been merged into "pyzmq" (yay!). And the main project, from what I have seen, actually includes all of the files that it ought, unlike my bootleg version over here. Please try switching to the plain "pyzmq" package, and let me know whether everything works!
