### ISSUE TITLE
merge into pyzmq, and related fixes

### ISSUE THREAD

**Issue by minrk** [brandon-rhodes/pyzmq-static#3]
Hi,

I think I have managed to bring the functionality of pyzmq-static [into pyzmq itself](https://github.com/zeromq/pyzmq/pull/205).  I did come across a few fixes for Windows and py3 compatibility, in the meantime:

```
* initlibzmq.c is different for py3
* use FD_SETSIZE define from libzmq msvc project
```

What do you think about bringing your future efforts to pyzmq itself rather than continuing to maintain pyzmq-static separately?

**Comment by brandon-rhodes** [comment]
Maintaining this functionality in pyzmq itself would save work on both sides, I suspect — I will get @borgstrom, who is helping me maintain pyzmq-static, to take a look at this too!

The current version of pyzmq-static is designed to work offline — if before going on a plane flight I check out a project repository that keeps its dependency .tar.gz files right in the repository, which is always my practice, then I expect to be able to get on the plane and create a virutalenv with all of those dependencies installed.

But it looks like you patch for pyzmq does not actually include libzmq and uuid inline. So if I tried to install pyzmq statically on the airplane flight without wifi, then the install would fail because it has to download those dependencies during the install itself. The project virtualenv, in other words, becomes un-rebuild-able without network connectivity.

Here is one way forward:
1. Your patches get accepted to the pyzmq project itself.
2. Many people can then install pyzmq using that logic.
3. pyzmq-static could switch to being plain pyzmq PLUS a few extra files thrown into the .tar.gz to include pyzmq and libuuid.

That way, all of the build logic for the static version would live in pyzmq where it would be well-maintained, BUT pyzmq itself would not need to bloat its .tar.gz with the pyzmq source code and the libuuid source code, that are only needed by people like me who depend on being able to rebuild a service — whether here on my laptop, or on an EC2 instance in production — without needing any other servers to be reachable anywhere to get the install done.

Does this make sense, given your understanding of the issues involved?

**Comment by brandon-rhodes** [comment]
Oh: and, we'd probably release one more pyzmq-static under the old system because we never did yet get around to releasing for 2.2.0, and we are getting close to ready to do that.

**Comment by minrk** [comment]
making a 2.2.0 pyzmq-static makes perfect sense.

Re: offline,

The pyzmq logic only downloads files if it doesn't already have them, so if you make a tarball with uuid and libzmq sources in pyzmq/bundled, then it will not try to fetch anything.  In my branch, `python setup.py configure --zmq=bundled` results in the directory being in such a state, so you can just zip it up and be done (I will make a specific command that only fetches, the command I mentioned does a little bit extra that you wouldn't want).  Since this tarball would, by definition, have no need to be discovered by pip/easy_install, then I am happy to make one for each release (e.g. pyzmq-with-deps.tar.gz) and host it at pyzmq.

**Comment by minrk** [comment]
Can I ask a bit more about your offline laptop/ec2 use case?  Do you ever use live repos, or just tarballs?  You obviously aren' using pip or easy_install to fetch, and git checkouts also assume some connectivity.  Would a simple tarball with the uuid/libzmq sources cover it?

For instance, to make such a tarball from current pyzmq-master:

``` bash
curl -o pyzmq-master.tar.gz -L https://github.com/zeromq/pyzmq/tarball/master
tar -xzf pyzmq-master.tar.gz
mv zeromq-pyzmq-* pyzmq # the name will be zeromq-pyzmq-<sha1>
cd pyzmq
python setup.py cython fetchbundle # cython step only needed from git, not sdists
cd ..
tar -czf pyzmq-with-deps.tar.gz pyzmq/
```

The result is a tarball that will never try to use a network connection to install.

**Comment by borgstrom** [comment]
Hi guys,

Pardon my lateness to the convo. I was in Montreal at a conference all week running an art installation I built.

I'm 100% for discontinuing pyzmq-static and merging the functionality into the mainline pyzmq tree.

@brandon-rhodes I actually think that this is a good time to stop pyzmq-static and push people to the mainline distro for the 2.2.0 release. My reasoning is that if we do release version 2.2.0 then we're on the hook for maintaining it, where as now we've covered the 2.1 series and it makes it nice and clean to end here.

@minrk I see your pull was closed a couple days ago. Nice work on getting this into mainline, if there's one thing I love it's simplicity. :)

**Comment by brandon-rhodes** [comment]
@minrk Each of my projects has a “packages” directory that looks something like this:

```
packages/
    SQLAlchemy/
        SQLAlchemy-0.6.6.tar.gz
    requests/
        requests-0.11.1.tar.gz
    ...
```

Assuming that those packages are named in my project's `setup.py` or `requirements.txt`, I can give `pip` the `-i` option to have it use this dedicated directory as though it were PyPI instead of going off to the Internet trying to make HTTP connections. For example, if `setup.py` is in the current directory `.`, then I can ask pip to set up the package in the current directory in development mode (`-e`):

```
pip install -i file://$PWD/packages -e .
```

Or a simpler project might not have a `setup.py` but have a `requirements.txt` instead, in which case I could install its dependencies in its virtual environment like this:

```
pip install -i file://$PWD/packages -r requirements.txt
```

Either way, by having a tiny local PyPI available with my dependencies in it, I put myself in the pleasant situation where I can either work on the project on an airplane, or get it going on an EC2 instance, even if I cannot reach PyPI. I always keep this directory of dependencies checked into version control to guarantee that, so long as I have a repository, I am guaranteed to be able to build a working app.

With that background, you will understand the importance of `pyzmq-static` carrying all of the source code of its dependencies inside of it — it means that `pyzmq` can be installed with the same guarantees as something like `requests`.

**Comment by minrk** [comment]
Thanks for clarifying.  It sounds like the pyzmq changes solve this case quite well.

It seems to me that pyzmq-static would no longer be defined as a separate project on PyPI, but rather a a separate tarball within pyzmq (I am happy to build a new one on each release, it's just one bash command), so it includes the libzmq sources.

This is the problem I want to avoid: I don't think it helps anyone for there to be projects listing pyzmq-static in requirements.txt, just to avoid downloads.  If you are already setting up a local PyPI, you can just use the everything-bundled tarball for pyzmq, rather than the default one, and everything should be hunky-dory.

Is that accurate?

**Comment by brandon-rhodes** [comment]
(Sorry for my delayed response; things have been pretty crazy here in Ohio, with the storms and our loss of things like power and Internet!)

I have attempted to build a “pyzmq-2.2dev.tar.gz” sdist but I cannot get it to then “pip install” in another virtualenv. Boy, there were a lot of errors ­— I suppose as it kept trying dead-end routes to getting everything compiled, then stepped back and tried again? The final error looked like:

```
bundled/zeromq/src/options.cpp:27:28: fatal error: ../include/zmq.h: No such file or directory

compilation terminated.

error: command 'gcc' failed with exit status 1
```

Yes, it was double-spaced like that; I am not sure why.

Anyway, I suppose that since the pull request has now been accepted, I can just go report this as a normal bug and everyone can get to work on it. But I first just wanted to check whether this sequence should have worked: getting pyzmq from github, building its sdist, and then trying to install that sdist — which, as I understand, is exactly the one that will be on PyPI? — in a fresh virtualenv.

In other news, the message about how to avoid the 10-second delay actually causes the naive user to encounter an error:

```
$ pip install --zmq=bundled ~/pyzmq/dist/pyzmq-2.2dev.tar.gz
Usage: /home/brandon/v/bin/pip install [OPTIONS] PACKAGE_NAMES...

/home/brandon/v/bin/pip install: error: no such option: --zmq
```

But, again, I can open an issue about that once you guys confirm for me whether I am going in the right direction here.

Oh, @minrk — with regards to your question: would the “everything bundled” sdist have exactly the same filename as the normal sdist? If so, how would people know which one was which when they looked at the filename?

**Comment by minrk** [comment]
> Sorry for my delayed response; things have been pretty crazy here in Ohio, with the storms and our loss of things like power and Internet!

No worries, I am glad to have your input on this stuff.

> I have attempted to build a “pyzmq-2.2dev.tar.gz” sdist but I cannot get it to then “pip install” in another virtualenv

Did you use the steps I provided above?  `setup.py sdist` will exclude the bundled zeromq sources.  I can confirm that a tarball created with those steps is installable on Ubuntu 12.04 and OS X without an internet connection or a prior install of libzmq.

>  I suppose as it kept trying dead-end routes to getting everything compiled, then stepped back and tried again?

Yes, if nothing is specified, it will try, in order:
1. try without specified libzmq (must be on default cc/ld path)
2. (posix-only) try explicit /usr/local (most likely default location)
3. fallback on libzmq as an Extension

> But I first just wanted to check whether this sequence should have worked: getting pyzmq from github, building its sdist, and then trying to install that sdist — which, as I understand, is exactly the one that will be on PyPI? — in a fresh virtualenv.

Yes, that's correct.  This sdist will require that you have an internet connection to fetch libzmq if it is not installed.  I assume your test had this?

> In other news, the message about how to avoid the 10-second delay actually causes the naive user to encounter an error:
> `$ pip install --zmq=bundled ~/pyzmq/dist/pyzmq-2.2dev.tar.gz`

That is an argument for setup.py, not pip, so it would be:

```
$ pip install ~/pyzmq/dist/pyzmq-2.2dev.tar.gz --install-option="--zmq=bundled"
```

If people want to pass arguments via pip, they should understand how to use pip.  I don't think it is appropriate for pyzmq to be teaching people about the difference between passing arguments to setup.py through pip, but maybe mentioning `--install-option` is worthwhile.

> with regards to your question: would the “everything bundled” sdist have exactly the same filename as the normal sdist?

No, it would have a different name, such as `pyzmq-bundled-libzmq-2.2.1.tar.gz`.  It mustn't have the same name, because it is important that pip _does not_ find it unless explicitly requested.  If you want to use this in your local mirror, then you can rename your copy, of course, but uninformed users should never encounter it.

**Comment by brandon-rhodes** [comment]
My head is clearer this morning: the whole message about “--zmq=bundled” is a bug if pyzmq is being installed as a dependency, because it is, so far as I can see, an option that is only available when _building_ the sdist, never when actually _using_ the sdist. In other words, all actual users — all of whom will simply mention “pyzmq” as a dependency in setup.py or requirements.txt, right? — will find the option unusable, because it simply generates the error message:

```
Fatal: Custom zmq directory "bundled" does not exist
```

when it runs from inside of the sdist. Am I correct, or should I have had coffee before answering? :)

I agree that it will be simpler that everyone who wants pyzmq will simply list “pyzmq” as their dependency. But I worry about confusion for the people renaming the “bundled” package, who then forget and think it's just the vanilla one and don't understand why their project now doesn't install reliably when “all I did was replace 2.3.1 with 2.3.2 and then two months later during that big outage we couldn't even spin up new instances because it kept complaining about some URLs it couldn't get to!”

The huge, huge issue here is that the difference between vanilla and bundled will be pretty much invisible to 99% of users 99% of the time: they tell their project to install, lots of stuff goes past the screen, and it's done. Only on the day that the 3rd party URLs go unavailable will they realize that pyzmq was only installing successfully because of 3rd party dependencies that they didn't even know it was going out on to the Internet to fetch.

Will the “bundled” tar.gz be uploaded to PyPI as well? (I have never checked whether PyPI would let me upload files with arbitrary names that do not quite match the name of the package itself.)

I would, I suppose, be vastly more comfortable if the sdist _always_ included the bundle, but then ignored it if the system offered a libzmq to link against. Then the `--zmq` option goes away, and having two versions of the .tar.gz goes away, and people having to rename the bundled version so that it still fits their "pyzmq" goes away, and vulnerability to shifting URLs goes away. Note that this whole download-on-the-fly scheme would have broken last year when libuuid changed the URL at which it lives — suddenly every single copy of pyzmq from PyPI would have stopped installing for thousands of people for whom it had installed successfully a few days before.

What is the difference in size between the .tar.gz if the source is simply always bundled?

**Comment by minrk** [comment]
On Jul 11, 2012, at 15:43, Brandon Craig
Rhodesreply@reply.github.com
wrote:

> My head is clearer this morning: the whole message about “--zmq=bundled” is a bug if pyzmq is being installed as a dependency, because it is, so far as I can see, an option that is only available when _building_ the sdist, never when actually _using_ the sdist. In other words, all actual users — all of whom will simply mention “pyzmq” as a dependency in setup.py or requirements.txt, right?

Yes that would be a bug, because it should fallback on bundled libzmq
without any user input if it cannot find any libzmq installed on the
system.  This has been my experience in all tests so far, but I do not
have a local PyPI mirror. I do not know what would be different on
your systems.  If you have Cython, you should be able to do `pip
install https://github.com/zeromq/pyzmq/tarball/master`

> — will find the option unusable, because it simply generates the error message:
> 
>    Fatal: Custom zmq directory "bundled" does not exist

That is the error you would see if it was using the current
pyzmq-2.2.0, but shouldn't happen with master.  I'm baffled by this,
but we can open an issue with further details about this over at
pyzmq.

> when it runs from inside of the sdist. Am I correct, or should I have had coffee before answering? :)

What should have happened is it would fallback on using the bundled
libzmq, and raised no errors. It looks to me like it used the
pyzmq-2.2.0 tarball, but if it did not, then there is a bug somewhere
in the new code.  Let's open an Issue on pyzmq to track this down in
detail.

Unfortunately, it is very difficult to figure out distribution issues
until I publish a new release.  I think I will do a trial release
(2.2.0-1) this weekend to test out this new code (and zmq.green), and
get some feedback, expecting to do another full release not too long
thereafter.

> I agree that it will be simpler that everyone who wants pyzmq will simply list “pyzmq” as their dependency. But I worry about confusion for the people renaming the “bundled” package, who then forget and think it's just the vanilla one and don't understand why their project now doesn't install reliably when “all I did was replace 2.3.1 with 2.3.2 and then two months later during that big outage we couldn't even spin up new instances because it kept complaining about some URLs it couldn't get to!”

I do agree that the confusion is not ideal, but I honestly don't think
it will come up, at least not much.

> The huge, huge issue here is that the difference between vanilla and bundled will be pretty much invisible to 99% of users 99% of the time: they tell their project to install, lots of stuff goes past the screen, and it's done. Only on the day that the 3rd party URLs go unavailable will they realize that pyzmq was only installing successfully because of 3rd party dependencies that they didn't even know it was going out on to the Internet to fetch.

It is only systems with offline PyPI mirrors that are affected by
this, which are necessarily managed by advanced users.  I don't think
it's too high a burden on those admins with the requirement for
offline installs to select the nonstandard just-for-them tarball.
Very nearly 100% of installs will be from PyPI/GitHub, which means
that a connection is available.

> Will the “bundled” tar.gz be uploaded to PyPI as well? (I have never checked whether PyPI would let me upload files with arbitrary names that do not quite match the name of the package itself.)

I had intended to put it on GitHub instead, as I didn't think there
would be a reason to put something on PyPI that setuptools can't find,
when GitHub downloads are so much faster and more reliable, but if
there is I'm happy to put it there. PyPI does allow arbitrary names,
so this is just a decision to make.

> I would, I suppose, be vastly more comfortable if the sdist _always_ included the bundle, but then ignored it if the system offered a libzmq to link against. Then the `--zmq` option goes away,

Nope, the --zmq option can never go away.  Remember, bundling libzmq
as an Extension will always be a fallback that should be avoided if
feasible.  It will never be preferable to building and installing
libzmq in a system-appropriate way, which is trivial on almost all
systems (especially after libzmq3, which UUID dependency is dropped in
libzmq-3).

> and having two versions of the .tar.gz goes away, and people having to rename the bundled version so that it still fits their "pyzmq" goes away, and vulnerability to shifting URLs goes away. Note that this whole download-on-the-fly scheme would have broken last year when libuuid changed the URL at which it lives  — suddenly every single copy of pyzmq from PyPI would have stopped installing for thousands of people for whom it had installed successfully a few days before.

This would only affect those users who do not have libzmq.  Up to and
including today, there are zero of these users of pyzmq itself, and I
hope that number never gets to 'thousands'.

It would feel a bit silly to make a release just to fix a URL, but I
really don't see that as a big deal.

If we don't trust the URLs to stick around (and perhaps we shouldn't),
I can mirror them on pyzmq's GitHub download area, which I do control.
 It seems like I shouldn't trust libuuid, but honestly I do trust
zeromq to preserve their URLs for current stable releases (pyzmq is
never more than two behind).  Since I trust zeromq itself, I expect
that I can get away with trusting libuuid for the months between now
and the first 3.x release.  Remember, this has no effect on a 'normal'
pyzmq install, so it will only affect this minority of users that
cannot (or will not) install libzmq in a normal fashion.

> What is the difference in size between the .tar.gz if the source is simply always bundled?

libzmq is bigger than pyzmq.

pyzmq with libzmq/uuid: 2.4MB
pyzmq-only sdist: 636kB

It seems extremely inefficient to quadruple the download size with
code that would be used by approximately zero users (and _should_ be
used by exactly zero).  If I prune unused files from libzmq (right now
it's dropped in whole), I can probably get it down to 1MB, but I am
not sure that is worth the complexity, and it is still adding a bunch
of totally unused code.

**Comment by stsci-sienkiew** [comment]
Reading the above discussion is disappointing to me.  I'm not following all the details, but it looks like I can summarize as:
- pyzmq-static is on the way out
- pyzmq will pick up some of the existing capability, but in a way that is difficult to use

I would hope that I could just download the pyzmq tar file and use it to do an install without downloading additional material from the internet.  That would give me some hope of configuration control in my application.  

(Yes, I know that 99% of users don't care about configuration management, so they can just "easy_install whatever" and take whatever they get.  I do care, though.)

**Comment by brandon-rhodes** [comment]
@minrk, thank you for all of this information ­— it is clearly not acceptable for “pyzmq” to increase in size by almost 2 MB in order to bundle its dependencies for the just-in-case scenario where the person doing the install lacks network connectivity in an emergency. (Though I will note that the most recent “pyzmq-static” was only 416 kB with the dependencies included — have they simply gotten a lot larger between 2.1 and 2.2?)

@stsci-sienkiew, thank you for convincing me that other people — and not just me! — worry about whether their tar.gz dependencies are truly self-contained, and installable without Internet access. I was starting to worry that I was bothering @minrk with a crazy-paranoid requirement!

I think that @stsci-sienkiew's life, as well as my own, will be simpler if the pyzmq-with-its-dependencies-inline-in-the-tar.gz:
1. Has a name of its own.
2. Can be downloaded from PyPI with that name.

Both of these will be satisfied if, with each pyzmq release, you release the dependencies-included version of the package under the name “pyzmq-static” on PyPI. I could do this for you if you find the task distasteful — but for people like me and @stsci-sienkiew, it provides the only simple way to make sure that our projects get the safe version of the package, repeatably, over and over again, as we upgrade to new versions of pyzmq. 

Either way, we succeed at getting rid of my separate “pyzmq-static” repository with its completely separate build process, and we get to focus all of our effort at “pyzmq” itself.

Does that sound like a survivable future?

**Comment by minrk** [comment]
Thanks for the feedback, it's really helpful.  Perhaps I underestimate this use case.  It doesn't make sense to bring in your great work to pyzmq, and then make it not useful for you anymore.

>  have they simply gotten a lot larger between 2.1 and 2.2?

@brandon-rhodes - I don't think it hasn't grown, it's just that pyzmq-static discarded all of the autotools stuff, and I haven't done that yet.  I can get it down to a reasonable size if I remove the ability to use libzmq's configure to generate platform.hpp, which may have been a silly thing to do in the first place.  Have you ever had anyone report that your provided platform.hpp was wrong?

Here's my current plan based on this:

I will ship the stripped libzmq/uuid in the pyzmq sdist (only the src/include/license files that pyzmq-static has been shipping).

Just one package, just one sdist, no internet connection needed unless building from a git snapshot.

How does that sound? Is there anything else that would need to be done for this to work for you?

[this](https://www.dropbox.com/s/9oeom7menbhy67i/pyzmq-2.2dev.tar.gz) ought to be a tarball created with that principle, if you want to give it a try (a civilized 800kB).

Where I would love your help is generating the new platform_freebsd.hpp when there are new releases.  I have regular access to linux and darwin, but not freebsd.

**Comment by brandon-rhodes** [comment]
**Wow!** That sounds great!

That is so generous of you! I know you really wanted to avoid making it larger. I will help in any way I can — for example, in helping figure out what parts are absolutely necessary so that it ships as little as possible.

I will be happy to help you put together the platform.hpp files for each release — and, no, I cannot recall its ever being a problem, which indeed surprised me. Either platforms have become very uniform these days in how their libc libraries are laid out (so all FreeBSD folks have machines that look identical so far as platform.hpp is concerned), or the libzmq code is not actually as sensitive as ./configure thinks it is to how the architecture makes calls. :)

**Comment by brandon-rhodes** [comment]
And that pyzmq-2.2dev.tar.gz file builds and installs perfectly for me, even with my Internet connection completely turned off. **Perfect!** Let me know what I can do at this point to help, and as soon as this is released I will update the pyzmq-static entry on PyPI with a big notice at the top pointing them back at pyzmq.

**Comment by minrk** [comment]
Okay, sounds good.  I will try to do a 2.2.0-1 release as a preview in the next week or so to get a feel for pip issues, with the expectation that I will have to do another not too long after with some fixes.

Thanks for the help!

**Comment by brandon-rhodes** [comment]
Just raising my head again since I have some spare cycles late this week and this weekend — anything you'd like me to try out or look at yet?

**Comment by minrk** [comment]
2.2.0.1 is up.  Let me know if you have any issues.  I expect there will be some silly issues that force a 2.2.0.2, but please do kick the tires!

**Comment by brandon-rhodes** [comment]
It works GREAT, @minrk — I am able to disable my network connectivity completely and, after a bit of complaint, it installs a built-in libzmq from source and Just Works for me! I will go figure out how to sunset pyzmq-static. THANK YOU!

**Comment by brandon-rhodes** [comment]
I have created a final version of pyzmq-static, version 2.2, that points users at the main "pyzmq" project from now on, and that has a tiny setup.py that depends upon "pyzmq" so that projects don't immediately break that have a bare non-versioned dependency on "pyzmq-static" — because I weighed things, and decided not to break people just for the sake of letting them know that it's time they switch names. I'd rather them discover that they can do that a bit late, than have a bad experience with Python packaging and package maintainers (since that happens often enough already!).

**Comment by minrk** [comment]
Makes perfect sense.  Do feel free to send any future PRs pyzmq's way.  Thanks for your help!
